server:
  port: 16270
spring:
  application:
    name: learn-prj
  profiles:
    active: 
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      auto-commit: true
#      connection-test-query: SELECT 1
#      connection-timeout: 30000
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      maximum-pool-size: 15
#      minimum-idle: 5
#      pool-name: DatebookHikariCP
#    password: root
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://127.0.0.1:3306/datebook?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: root


#mybatis:
#  type-aliases-package: com.elane.entity
#  mapper-locations: classpath:com/elane/dao/**/*.xml
#
#mapper:
#  mappers:
#    - com.elane.dao
#  not-empty: false
#  identity: postgresql
#
#pagehelper:
#  helperDialect: postgresql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
